[package]
name = "dh-key-exchange"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.9.0"
x25519-dalek = "2.0.0"
rand = "0.8.5"